// Generated by LiveScript 1.5.0
(function(){
  var ref$, valid, invalid, validateEmail;
  ref$ = require('./resolutions'), valid = ref$.valid, invalid = ref$.invalid;
  validateEmail = function(input){
    if (input.indexOf('@') === -1) {
      return invalid('E-postadress måste innehålla @.');
    }
    if (/@.*@/.test(input)) {
      return invalid('E-postadress får inte innehålla fler än ett @.');
    }
    if (!/.@/.test(input)) {
      return invalid('E-postadress måste innehålla ett namn före @.');
    }
    if (!/@./.test(input)) {
      return invalid('E-postadress måste innehålla en webbadress efter @.');
    }
    if (!/@.+\.[^.]{2,}$/.test(input)) {
      return invalid('E-postadressen måste sluta med .se .com .nu eller liknande.');
    }
    if (/@.+\.\./.test(input)) {
      return invalid('E-postdomän kan inte innehålla två punkter efter varandra.');
    }
    return valid();
  };
  module.exports = validateEmail;
}).call(this);
