// Generated by LiveScript 1.5.0
(function(){
  var ref$, invalid, valid, validateEmployerPhone;
  ref$ = require('./resolutions'), invalid = ref$.invalid, valid = ref$.valid;
  validateEmployerPhone = function(input){
    if (!/^\+?\d{5,25}$/.test(input)) {
      return invalid('Vänligen ange ett telefonnummer till din arbetsgivare.');
    }
    return valid();
  };
  module.exports = validateEmployerPhone;
}).call(this);
