// Generated by LiveScript 1.5.0
(function(){
  var moment, ref$, invalid, valid, validateEmployementSince;
  moment = require('moment');
  ref$ = require('./resolutions'), invalid = ref$.invalid, valid = ref$.valid;
  validateEmployementSince = function(input, arg$){
    var now, employmentSinceMonth, year, month, employmentSince;
    now = arg$.now, employmentSinceMonth = arg$.employmentSinceMonth;
    if (!/^(\d+)$/.test(input)) {
      return invalid('Ange året du började, endast siffror (tex: 2010).');
    }
    year = parseInt(input, 10);
    if (year < 1000) {
      return invalid('Ange året du började, fyra siffror (tex: 2010).');
    }
    if (year < 1900) {
      return invalid('Ange året du började (tex: 2010).');
    }
    month = employmentSinceMonth || 0;
    employmentSince = moment({
      year: year,
      month: month
    });
    if (employmentSince.isAfter(now)) {
      return invalid('Anställningsdatumet kan inte vara i framtiden.');
    }
    return valid();
  };
  module.exports = validateEmployementSince;
}).call(this);
