// Generated by LiveScript 1.5.0
(function(){
  var ref$, invalid, valid, validateHomeCost;
  ref$ = require('./resolutions'), invalid = ref$.invalid, valid = ref$.valid;
  validateHomeCost = function(input){
    var value;
    if (!/^(\d+)$/.test(input)) {
      return invalid('Använd siffror, tack.');
    }
    value = parseInt(input, 10);
    if (value < 0) {
      return invalid('Ange månadskostnad för ditt boende.');
    }
    return valid();
  };
  module.exports = validateHomeCost;
}).call(this);
