// Generated by LiveScript 1.5.0
(function(){
  var ref$, invalid, valid, validateIncome;
  ref$ = require('./resolutions'), invalid = ref$.invalid, valid = ref$.valid;
  validateIncome = function(input){
    var value;
    if (!/^(\d+)$/.test(input)) {
      return invalid('Använd siffror, tack.');
    }
    value = parseInt(input, 10);
    if (value < 10000) {
      return invalid('Dessvärre måste du tjäna minst 10\xA0000\xA0kr i månaden för att jämföra lån via Advisa.');
    }
    if (value > 99999) {
      return invalid('För högt belopp angett.');
    }
    return valid();
  };
  module.exports = validateIncome;
}).call(this);
