// Generated by LiveScript 1.5.0
(function(){
  module.exports = {
    email: require('./email'),
    employerPhone: require('./employer-phone'),
    homeCost: require('./home-cost'),
    mobilePhone: require('./mobile-phone'),
    numDependants: require('./num-dependants'),
    personnummer: require('./personnummer'),
    repaymentTime: require('./repayment-time'),
    totalLoan: require('./total-loan'),
    income: require('./income'),
    employedSince: require('./employed-since'),
    employedTo: require('./employed-to')
  };
}).call(this);
