// Generated by LiveScript 1.5.0
(function(){
  var ref$, invalid, valid, validateMobilePhone;
  ref$ = require('./resolutions'), invalid = ref$.invalid, valid = ref$.valid;
  validateMobilePhone = function(input){
    if (!/^((00|\+)?46|0)/.test(input)) {
      return invalid('Måste börja med 0 eller svensk landskod (+46).');
    }
    if (!/^((00|\+)?46|0)7[023469]\d{7}$/.test(input)) {
      return invalid('Telefonnumret verkar vara felaktigt angett. Vänligen ange ett giltigt, svenskt mobiltelefonnummer.');
    }
    return valid();
  };
  module.exports = validateMobilePhone;
}).call(this);
