// Generated by LiveScript 1.5.0
(function(){
  var ref$, invalid, valid, loanMinYears, loanMaxYears, validateRepaymentTime;
  ref$ = require('./resolutions'), invalid = ref$.invalid, valid = ref$.valid;
  ref$ = require('../../../../../config/company'), loanMinYears = ref$.loanMinYears, loanMaxYears = ref$.loanMaxYears;
  validateRepaymentTime = function(input){
    var value;
    if (!/^(\d+)$/.test(input)) {
      return invalid('Använd siffror, tack.');
    }
    value = parseInt(input, 10);
    if (value < loanMinYears) {
      return invalid("Kortast tillåtna återbetalningstid är " + loanMinYears + " år.");
    }
    if (value > loanMaxYears) {
      return invalid("Längsta tillåtna återbetalningstid är " + loanMaxYears + " år.");
    }
    return valid();
  };
  module.exports = validateRepaymentTime;
}).call(this);
