// Generated by LiveScript 1.5.0
(function(){
  module.exports.invalid = function(message){
    return {
      valid: false,
      message: message
    };
  };
  module.exports.valid = function(){
    return {
      valid: true
    };
  };
}).call(this);
